### PR TITLE
options to customize font family/size for messages

### PR DESCRIPTION
**Pull request by ddanilov**

### CODE REVIEW

**Comment by rpallai** [comment]
@ddanilov: I'm pretty sure that the same font should be used in the `authorLabel` if `xchatStyle` is in use.

**Comment by rpallai** [comment]
I'm very exicted about this feature so I made a step forward: https://github.com/rpallai/Quaternion/commit/b41ac0ee9d417d83d7952aaf8415327e4e8e21dc

How to continue?

**Comment by KitsuneRal** [comment]
I asked @ddanilov in the Quotient room - if he's around and available for hacking, then please collaborate. If not, you can make a "competing" PR.

**Comment by KitsuneRal** [comment]
> I'm very exicted about this feature so I made a step forward: [rpallai@b41ac0e](https://github.com/rpallai/Quaternion/commit/b41ac0ee9d417d83d7952aaf8415327e4e8e21dc)
> 
> How to continue?

As Denis mentioned in the Matrix room - feel free to base your own PR on this.

**Comment by rpallai** [comment]
Ok, let's continue in #614

**Pull request closed without merging**
